package(default_visibility = ['//visibility:public'])

load("//third_party/protobuf:protobuf.bzl", "cc_proto_library")

cc_proto_library(
    name = 'birthday_meta_proto',
    srcs = ['birthday_meta.proto'],
)
